services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payments"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - rinha-network

  api1:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=payments
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=9999
      - WORKER_COUNT=25
      - QUEUE_BUFFER_SIZE=12000
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - LOG_LEVEL=error
      - LOG_FORMAT=text
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rinha-network
      - payment-processor
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 70MB

  api2:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=payments
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=9999
      - WORKER_COUNT=25
      - QUEUE_BUFFER_SIZE=12000
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - LOG_LEVEL=error
      - LOG_FORMAT=text
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rinha-network
      - payment-processor
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 70MB

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    networks:
      - rinha-network
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 30MB

volumes:
  postgres_data:

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true
