services:
  # PostgreSQL Database - Otimizado para usar menos recursos
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--data-checksums"
    command: >
      postgres
      -c shared_buffers=32MB
      -c effective_cache_size=64MB
      -c maintenance_work_mem=6MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=6MB
      -c default_statistics_target=50
      -c random_page_cost=1.1
      -c effective_io_concurrency=100
      -c work_mem=1MB
      -c min_wal_size=256MB
      -c max_wal_size=1GB
      -c max_connections=150
      -c max_prepared_transactions=150
      -c shared_preload_libraries='pg_stat_statements'
      -c wal_level=replica
      -c max_wal_senders=2
      -c max_replication_slots=2
      -c hot_standby=on
      -c hot_standby_feedback=on
      -c log_statement=none
      -c log_duration=off
      -c log_min_duration_statement=10000
      -c log_checkpoints=off
      -c log_connections=off
      -c log_disconnections=off
      -c log_lock_waits=on
      -c deadlock_timeout=1s
      -c lock_timeout=5s
      -c statement_timeout=30s
      -c idle_in_transaction_session_timeout=60s
      -c tcp_keepalives_idle=300
      -c tcp_keepalives_interval=30
      -c tcp_keepalives_count=3
      -c fsync=off
      -c synchronous_commit=off
      -c wal_compression=on
      -c wal_writer_delay=500ms
      -c checkpoint_timeout=30min
      -c checkpoint_flush_after=256kB
      -c bgwriter_delay=500ms
      -c bgwriter_lru_maxpages=50
      -c bgwriter_lru_multiplier=2.0
      -c bgwriter_flush_after=512kB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: 155MB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d payments" ]
      interval: 15s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  # API Instance 1 - Otimizada (recursos redistribuídos)
  api1:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=payments
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=9999
      - WORKER_COUNT=25
      - QUEUE_BUFFER_SIZE=12000
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - postgres
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 90MB

  # API Instance 2 - Otimizada (recursos redistribuídos)
  api2:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=payments
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=9999
      - WORKER_COUNT=25
      - QUEUE_BUFFER_SIZE=12000
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - postgres
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 90MB

  # Nginx Load Balancer - Otimizado (recursos redistribuídos)
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 35MB

volumes:
  postgres_data:

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true
