version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rinha-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - rinha-network

  # API Instance 1
  api1:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=payments
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=9999
    depends_on:
      - postgres
      - redis
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 200M

  # API Instance 2
  api2:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=payments
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=9999
    depends_on:
      - postgres
      - redis
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 200M

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 100M

volumes:
  postgres_data:

networks:
  rinha-network:
    driver: bridge
