version: '3.8'

services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=db user=postgres password=postgres dbname=rinha_db sslmode=disable"
      PAYMENT_PROCESSOR_URL_DEFAULT: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_URL_FALLBACK: "http://payment-processor-fallback:8080"
      QUEUE_BUFFER_SIZE: "15000"
      QUEUE_WORKER_COUNT: "8"
    networks:
      - backend
      - payment-processor
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=db user=postgres password=postgres dbname=rinha_db sslmode=disable"
      PAYMENT_PROCESSOR_URL_DEFAULT: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_URL_FALLBACK: "http://payment-processor-fallback:8080"
      QUEUE_BUFFER_SIZE: "15000"
      QUEUE_WORKER_COUNT: "8"
    networks:
      - backend
      - payment-processor
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_db
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "300MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

